//! Memory protocol — write, read, and list handoff artifacts under `memory/artifacts/`.
//!
//! Artifacts are YAML-frontmatter + Markdown files. The frontmatter is the machine
//! contract; the body is free-form Markdown for the resuming agent. The rendered file
//! (not just the stdin body) is scanned for secrets before anything hits disk.
//!
//! See docs/specs/2026-06-08-memory-research-first.md for the full protocol.

use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::instinct::validate_id;
use crate::scan::{load_rules, scan_bytes_for_secrets};

// ---------- helpers ----------

/// `YYYY-MM-DD`, checked without a date crate (shape only — no wall clock).
fn is_iso_date(s: &str) -> bool {
    let b = s.as_bytes();
    b.len() == 10
        && b[4] == b'-'
        && b[7] == b'-'
        && b[..4].iter().all(u8::is_ascii_digit)
        && b[5..7].iter().all(u8::is_ascii_digit)
        && b[8..10].iter().all(u8::is_ascii_digit)
}

/// Run `git -C <root> <args>`, returning trimmed stdout on success or `None`.
fn git_run(root: &Path, args: &[&str]) -> Option<String> {
    let out = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .output()
        .ok()?;
    if out.status.success() {
        Some(String::from_utf8_lossy(&out.stdout).trim_end().to_string())
    } else {
        None
    }
}

/// Returns `(branch, head_sha)`. Degrades to empty strings off a repo — deliberate policy: a
/// handoff can be written anywhere. Differs from `review.rs` which errors when git is absent.
pub(crate) fn git_info(root: &Path) -> (String, String) {
    let branch = git_run(root, &["rev-parse", "--abbrev-ref", "HEAD"]).unwrap_or_default();
    let sha = git_run(root, &["rev-parse", "HEAD"]).unwrap_or_default();
    (branch, sha)
}

/// Build the rendered artifact: a generated-by header, YAML frontmatter, blank line, body.
pub(crate) fn render(
    slug: &str,
    date: &str,
    branch: &str,
    sha: &str,
    status: &str,
    verified_by: &str,
    body: &str,
) -> String {
    let mut out = String::new();
    out.push_str("<!-- generated by gatekeeper memory write — do not edit by hand -->\n");
    out.push_str("---\n");
    out.push_str(&format!("feature: {slug}\n"));
    out.push_str(&format!("created: {date}\n"));
    out.push_str(&format!("branch: {branch}\n"));
    out.push_str(&format!("head_sha: {sha}\n"));
    out.push_str(&format!("status: {status}\n"));
    out.push_str(&format!("verified_by: {verified_by}\n"));
    out.push_str("---\n");
    out.push('\n');
    out.push_str(body);
    // Ensure a trailing newline.
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Hand-parse the YAML frontmatter of a handoff artifact and return `(created, status)`.
/// Returns `None` if the frontmatter is absent or malformed (the caller skips the file).
fn parse_frontmatter(text: &str) -> Option<(String, String)> {
    // Skip an optional leading HTML comment line (the generated-by header).
    let text = text.trim_start_matches('\n');
    let text = if text.starts_with("<!--") {
        text.lines()
            .skip_while(|l| !l.contains("-->"))
            .skip(1)
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        text.to_string()
    };
    let text = text.trim_start_matches('\n');
    let after_open = text.strip_prefix("---\n")?;
    let mut created = String::new();
    let mut status = String::new();
    for line in after_open.lines() {
        if line.trim() == "---" {
            break;
        }
        if let Some(rest) = line.strip_prefix("created:") {
            created = rest.trim().to_string();
        } else if let Some(rest) = line.strip_prefix("status:") {
            status = rest.trim().to_string();
        }
    }
    if created.is_empty() && status.is_empty() {
        return None;
    }
    Some((created, status))
}

// ---------- arg parsing ----------

fn parse_args(args: &[String]) -> (Option<String>, Option<String>, Option<String>) {
    let mut feature: Option<String> = None;
    let mut date: Option<String> = None;
    let mut status: Option<String> = None;
    let mut i = 1usize; // skip subcommand at index 0
    while i < args.len() {
        match args[i].as_str() {
            "--feature" => {
                feature = args.get(i + 1).cloned();
                i += 2;
            }
            "--date" => {
                date = args.get(i + 1).cloned();
                i += 2;
            }
            "--status" => {
                status = args.get(i + 1).cloned();
                i += 2;
            }
            _ => {
                i += 1;
            }
        }
    }
    (feature, date, status)
}

// ---------- subcommands ----------

fn cmd_write(args: &[String], root: &Path) -> i32 {
    let (feature_opt, date_opt, status_opt) = parse_args(args);

    let slug = match feature_opt {
        Some(s) if !s.is_empty() => s,
        _ => {
            eprintln!("gatekeeper memory write: --feature <slug> is required");
            return 2;
        }
    };
    if let Err(e) = validate_id(&slug) {
        eprintln!("gatekeeper memory write: invalid --feature: {e}");
        return 2;
    }
    let date = match date_opt {
        Some(d) if !d.is_empty() => d,
        _ => {
            eprintln!("gatekeeper memory write: --date <YYYY-MM-DD> is required");
            return 2;
        }
    };
    if !is_iso_date(&date) {
        eprintln!("gatekeeper memory write: --date must be YYYY-MM-DD, got '{date}'");
        return 2;
    }
    let status = status_opt.as_deref().unwrap_or("in-progress").to_string();

    // Read verified_by from args or default to empty.
    let verified_by = {
        let mut v = String::new();
        let mut i = 1usize;
        while i < args.len() {
            if args[i] == "--verified-by" {
                if let Some(val) = args.get(i + 1) {
                    v = val.clone();
                }
                break;
            }
            i += 1;
        }
        v
    };

    // Read body from stdin.
    let mut body = Vec::new();
    if std::io::stdin().lock().read_to_end(&mut body).is_err() {
        eprintln!("gatekeeper memory write: failed to read stdin");
        return 1;
    }
    let body_str = String::from_utf8_lossy(&body).into_owned();

    // Reject a body that opens a second frontmatter block.
    // A body that itself starts with `---` would create a double-frontmatter artifact.
    {
        let trimmed = body_str.trim_start_matches('\n');
        if trimmed.starts_with("---") {
            // Allow if it is only in a comment, but a bare `---` at start of body is rejected.
            eprintln!(
                "gatekeeper memory write: body must not open a second '---' frontmatter block"
            );
            return 2;
        }
    }

    // Build the rendered artifact.
    let (branch, sha) = git_info(root);
    let rendered = render(
        &slug,
        &date,
        &branch,
        &sha,
        &status,
        &verified_by,
        &body_str,
    );

    // Scan the RENDERED bytes for secrets (catches branch/feature names too).
    let rules_path = root.join("security").join("rules.toml");
    match load_rules(&rules_path) {
        Ok(rules) => {
            if let Err(hint) = scan_bytes_for_secrets(&rules, rendered.as_bytes()) {
                eprintln!("gatekeeper memory write: secret refusal — {hint}");
                return 1;
            }
        }
        Err(e) => {
            eprintln!("gatekeeper memory write: cannot load rules: {e}");
            return 2;
        }
    }

    // If status == "done", require verified_by to resolve to an existing docs/verify/*<slug>*.md.
    if status == "done" {
        let vb = verified_by.trim();
        if vb.is_empty() {
            eprintln!(
                "gatekeeper memory write: status 'done' requires --verified-by resolving to docs/verify/*{slug}*.md"
            );
            return 1;
        }
        // Use find_doc to locate docs/verify/<something-containing-slug>.md.
        match crate::find_doc("verify", &slug) {
            Some(_) => {}
            None => {
                eprintln!(
                    "gatekeeper memory write: status 'done' requires docs/verify/*{slug}*.md to exist"
                );
                return 1;
            }
        }
    }

    // Create artifacts directory and write the file.
    let artifacts_dir = root.join("memory").join("artifacts");
    if let Err(e) = fs::create_dir_all(&artifacts_dir) {
        eprintln!("gatekeeper memory write: cannot create memory/artifacts/: {e}");
        return 1;
    }
    let out_path = artifacts_dir.join(format!("{slug}.handoff.md"));
    if let Err(e) = fs::write(&out_path, rendered.as_bytes()) {
        eprintln!(
            "gatekeeper memory write: cannot write {}: {e}",
            out_path.display()
        );
        return 1;
    }
    println!("wrote memory/artifacts/{slug}.handoff.md");
    0
}

fn cmd_read(args: &[String], root: &Path) -> i32 {
    let (feature_opt, _, _) = parse_args(args);
    let slug = match feature_opt {
        Some(s) if !s.is_empty() => s,
        _ => {
            eprintln!("gatekeeper memory read: --feature <slug> is required");
            return 2;
        }
    };
    let path = root
        .join("memory")
        .join("artifacts")
        .join(format!("{slug}.handoff.md"));
    match fs::read_to_string(&path) {
        Ok(content) => {
            print!("{content}");
            0
        }
        Err(_) => {
            eprintln!("gatekeeper memory read: memory/artifacts/{slug}.handoff.md not found");
            1
        }
    }
}

fn cmd_list(root: &Path) -> i32 {
    let artifacts_dir = root.join("memory").join("artifacts");
    let rd = match fs::read_dir(&artifacts_dir) {
        Ok(rd) => rd,
        Err(_) => {
            // No artifacts directory: silently succeed with no output.
            return 0;
        }
    };
    let mut entries: Vec<PathBuf> = rd.filter_map(|e| e.ok().map(|e| e.path())).collect();
    entries.sort();
    for path in entries {
        let fname = match path.file_name() {
            Some(n) => n.to_string_lossy().to_string(),
            None => continue,
        };
        if !fname.ends_with(".handoff.md") {
            continue;
        }
        let slug = fname.trim_end_matches(".handoff.md").to_string();
        let text = fs::read_to_string(&path).unwrap_or_default();
        let (created, status) = parse_frontmatter(&text).unwrap_or_default();
        println!("{slug} · {created} · {status}");
    }
    0
}

// ---------- public entry point ----------

pub fn cmd_memory(args: &[String], root: &Path) -> i32 {
    let Some(sub) = args.first().map(String::as_str) else {
        eprintln!("gatekeeper memory: missing subcommand (write|read|list)");
        return 2;
    };
    match sub {
        "write" => cmd_write(args, root),
        "read" => cmd_read(args, root),
        "list" => cmd_list(root),
        other => {
            eprintln!("gatekeeper memory: unknown subcommand '{other}' (expected write|read|list)");
            2
        }
    }
}

// ---------- tests ----------

#[cfg(test)]
mod tests {
    use super::*;

    // ---------- pure-function tests ----------

    #[test]
    fn render_round_trips_frontmatter() {
        let out = render(
            "my-feature",
            "2026-06-08",
            "feat/my-feature",
            "abc1234",
            "in-progress",
            "",
            "## Goal\nSomething.\n",
        );
        assert!(out.contains("feature: my-feature\n"));
        assert!(out.contains("created: 2026-06-08\n"));
        assert!(out.contains("branch: feat/my-feature\n"));
        assert!(out.contains("head_sha: abc1234\n"));
        assert!(out.contains("status: in-progress\n"));
        assert!(out.contains("verified_by: \n"));
        assert!(out.contains("## Goal\nSomething.\n"));
        // Round-trip through the frontmatter parser.
        let (created, status) = parse_frontmatter(&out).expect("frontmatter must parse");
        assert_eq!(created, "2026-06-08");
        assert_eq!(status, "in-progress");
    }

    #[test]
    fn is_iso_date_accepts_valid() {
        assert!(is_iso_date("2026-06-08"));
        assert!(is_iso_date("2000-01-01"));
    }

    #[test]
    fn is_iso_date_rejects_malformed() {
        assert!(!is_iso_date("2026-6-8"));
        assert!(!is_iso_date("26-06-08"));
        assert!(!is_iso_date("2026/06/08"));
        assert!(!is_iso_date("not-a-date"));
        assert!(!is_iso_date(""));
    }

    #[test]
    fn parse_frontmatter_extracts_fields() {
        let text = "<!-- generated -->\n---\nfeature: foo\ncreated: 2026-01-01\nbranch: main\nhead_sha: abc\nstatus: done\nverified_by: some-note\n---\n\nbody\n";
        let (created, status) = parse_frontmatter(text).unwrap();
        assert_eq!(created, "2026-01-01");
        assert_eq!(status, "done");
    }

    #[test]
    fn scan_bytes_for_secrets_ok_on_clean() {
        use crate::scan::parse_rules_pub;
        let toml = "schema_version = 1\n\n\
                    [[rule]]\n\
                    id = \"aws\"\nkind = \"content\"\nseverity = \"block\"\n\
                    description = \"AWS key\"\n\
                    pattern = '\\b(AKIA|ASIA)[0-9A-Z]{16}\\b'\n";
        let rules = parse_rules_pub(toml).unwrap();
        assert!(scan_bytes_for_secrets(&rules, b"nothing here\n").is_ok());
    }

    #[test]
    fn scan_bytes_for_secrets_err_on_key() {
        use crate::scan::parse_rules_pub;
        let toml = "schema_version = 1\n\n\
                    [[rule]]\n\
                    id = \"aws\"\nkind = \"content\"\nseverity = \"block\"\n\
                    description = \"AWS key\"\n\
                    pattern = '\\b(AKIA|ASIA)[0-9A-Z]{16}\\b'\n";
        let rules = parse_rules_pub(toml).unwrap();
        let key = format!("AKIA{}", "1234567890ABCDEF");
        let result = scan_bytes_for_secrets(&rules, key.as_bytes());
        assert!(result.is_err(), "should detect AWS key");
        // The error hint must NOT contain the actual key value.
        let hint = result.unwrap_err();
        assert!(
            !hint.contains(&key),
            "hint must not contain the matched value"
        );
    }

    #[test]
    fn scan_bytes_for_secrets_handles_nul_bytes() {
        use crate::scan::parse_rules_pub;
        let toml = "schema_version = 1\n\n\
                    [[rule]]\n\
                    id = \"aws\"\nkind = \"content\"\nseverity = \"block\"\n\
                    description = \"AWS key\"\n\
                    pattern = '\\b(AKIA|ASIA)[0-9A-Z]{16}\\b'\n";
        let rules = parse_rules_pub(toml).unwrap();
        // NUL bytes interspersed with clean content: must not panic or misdetect.
        let mut payload = vec![0x00, 0xff, 0x00];
        payload.extend_from_slice(b"benign text\n");
        assert!(scan_bytes_for_secrets(&rules, &payload).is_ok());
        // NUL bytes followed by an AWS key: must still detect.
        let key = format!("AKIA{}", "1234567890ABCDEF");
        let mut payload2 = vec![0x00, b'\n'];
        payload2.extend_from_slice(key.as_bytes());
        let result = scan_bytes_for_secrets(&rules, &payload2);
        assert!(result.is_err(), "must detect key even after NUL bytes");
    }
}
