#!/usr/bin/env bash
# sync-gitleaks-rules.sh — refresh a REVIEW file of provider-prefix secret rules from gitleaks.
#
# This NEVER edits security/rules.toml (a protected path). It produces a review artifact,
# security/rules.gitleaks-review.toml, and prints which curated provider rules are NEW vs. the
# ones we already ship — a human then copies the wanted rules into rules.toml by hand. Run
# quarterly. The constraint-compatible substitute for vendoring gitleaks (ADR-0007: no runtime
# deps; ADR-0018 records the sync mechanism). Offline-guarded: a no-op (exit 0) without network,
# so CI never makes a network call.
set -euo pipefail

# Pinned upstream so a sync is reproducible and the provenance is auditable. The maintainer sets a
# real gitleaks commit SHA here before a sync; until then the script no-ops on the unresolvable pin
# (an honest placeholder, never a fake-looking SHA). Bump deliberately, human-reviewed each time.
GITLEAKS_SHA="${GITLEAKS_SHA:-PIN_A_REAL_GITLEAKS_COMMIT_SHA}"
GITLEAKS_RAW="https://raw.githubusercontent.com/gitleaks/gitleaks/${GITLEAKS_SHA}/config/gitleaks.toml"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RULES="${REPO_ROOT}/security/rules.toml"
REVIEW="${REPO_ROOT}/security/rules.gitleaks-review.toml"

# Curated provider-prefix subset: id|description|pattern (single-quoted-in-TOML on emit). These are
# label/prefix-anchored provider tokens that complement our existing rules; entropy (ADR-0018)
# covers the unlabeled classes. Hand-maintained and human-reviewed — never auto-merged.
CURATED=(
  "stripe-secret-key|Stripe secret key|\\bsk_live_[0-9A-Za-z]{24,}\\b"
  "sendgrid-api-key|SendGrid API key|\\bSG\\.[0-9A-Za-z_-]{22}\\.[0-9A-Za-z_-]{43}\\b"
  "twilio-api-key|Twilio API key|\\bSK[0-9a-fA-F]{32}\\b"
  "npm-access-token|npm access token|\\bnpm_[0-9A-Za-z]{36}\\b"
  "gitlab-pat|GitLab personal access token|\\bglpat-[0-9A-Za-z_-]{20}\\b"
  "google-api-key|Google API key|\\bAIza[0-9A-Za-z_-]{35}\\b"
)

offline_noop() {
  echo "sync-gitleaks: $1 — skipping (no-op). Re-run with network access to refresh the review file." >&2
  exit 0
}

# Offline guard: no network in CI, and a clean no-op for any offline run.
[ "${CI:-}" = "true" ] && offline_noop "running in CI"
[ "${1:-}" = "--offline" ] && offline_noop "--offline requested"
command -v curl >/dev/null 2>&1 || offline_noop "curl not found"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
if ! curl -fsSL --max-time 20 "$GITLEAKS_RAW" -o "$tmp" 2>/dev/null; then
  offline_noop "could not fetch ${GITLEAKS_RAW}"
fi

# Emit the curated subset in our schema, with a provenance header. Sanity-flag any curated rule
# whose id is not present upstream (curation drift), but still emit it for the human to judge.
{
  echo "# GENERATED REVIEW FILE — do NOT commit as security/rules.toml."
  echo "# synced-from: gitleaks@${GITLEAKS_SHA}"
  echo "# Generated by scripts/sync-gitleaks-rules.sh. A human curates which rules to copy into"
  echo "# security/rules.toml (a protected path); this file is never auto-merged."
  echo "schema_version = 2"
  echo ""
  for entry in "${CURATED[@]}"; do
    IFS='|' read -r id desc pattern <<<"$entry"
    grep -q "$id" "$tmp" || echo "# WARNING: curated id '${id}' not found in upstream gitleaks.toml (curation drift)"
    echo "[[rule]]"
    echo "id = \"${id}\""
    echo "kind = \"content\""
    echo "severity = \"warn\""
    echo "description = \"${desc} (synced from gitleaks)\""
    echo "pattern = '${pattern}'"
    echo ""
  done
} >"$REVIEW"

echo "sync-gitleaks: wrote review file ${REVIEW} (synced-from gitleaks@${GITLEAKS_SHA})."
echo ""
echo "Curated provider rules NOT yet in security/rules.toml (candidates to add by hand):"
for entry in "${CURATED[@]}"; do
  id="${entry%%|*}"
  if grep -q "id = \"${id}\"" "$RULES"; then
    echo "  already present: ${id}"
  else
    echo "  NEW: ${id}"
  fi
done
echo ""
echo "Review the diff, then manually copy wanted rules into security/rules.toml:"
echo "  diff -u <(grep -E '^id = ' \"$RULES\") <(grep -E '^id = ' \"$REVIEW\") || true"
